# Setup
title:        CRC
tagline:      The official body representing Canadian Student Rocketry Teams
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Simon Bambey
  url:        

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown